### ISSUE TITLE
Changing blueprint identifier does not update resource.

### ISSUE THREAD

**Issue by mgapp12** [port-labs/terraform-provider-port-labs#85] opened 2023-10-11 14:19 UTC
The following message was received during changing of the blueprint identifier as a typo was found. I would expect that i can change the identifier through terraform similar to how it is done in the ui.

│ failed to create blueprint, got:
│ {"ok":false,"error":"not_found","message":"Blueprint with identifier
│ \"k8s_cluster\" was not
│ found","details":{"resource":"Blueprint","byField":"identifier","withValue":"k8s_cluster"}}

the change that was made. 

  identifier = "k8s_cluste" 
to
  identifier = "k8s_cluster"
  
  the plan output:

  ~ resource "port_blueprint" "k8s-cluster" {
      ~ id         = "k8s_cluste" -> (known after apply)
      ~ identifier = "k8s_cluste" -> "k8s_cluster"
        # (5 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

**Comment by dvirsegev** [comment] 2023-10-22 08:39
Hey @mgapp12 , The issue is fixed on version `v.1.6.5`

**Closed by dvirsegev** 2023-10-22 08:39 UTC
